services:
  db:
    image: postgres:16
    container_name: postgres_contratos
    restart: always
    environment:
      POSTGRES_USER: admin_contratos
      POSTGRES_PASSWORD: strong_password_123
      POSTGRES_DB: db_contratos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
