### Atualizar Status do Rascunho para REVISAO

# Altere {ID_DO_RASCUNHO} para o ID real do rascunho que você quer atualizar
# Altere SEU_TOKEN_JWT para o seu token de acesso JWT válido
PATCH http://127.0.0.1:8000/api/rascunhos/3/update_status/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxNTkyNDQyLCJpYXQiOjE3NjE1ODg4NDIsImp0aSI6ImE5Mzc1ZjZkYzE0ZjQ3Nzg5ZTc4NDc3NmMyYmZiNDI2IiwidXNlcl9pZCI6IjEifQ.A0vb8JGaLspJp5nD-ORCD8b2k5lfGTL8MXv_1Zlz0tY
Content-Type: application/json

{
  "status": "REVISAO"
}

### Atualizar Status do Rascunho para FINALIZADO (Exemplo)

# Altere {ID_DO_RASCUNHO} para o ID real do rascunho que você quer atualizar
# Altere SEU_TOKEN_JWT para o seu token de acesso JWT válido
PATCH http://127.0.0.1:8000/api/rascunhos/{ID_DO_RASCUNHO}/update_status/
Authorization: Bearer SEU_TOKEN_JWT
Content-Type: application/json

{
  "status": "FINALIZADO"
}


### Tentar Atualizar Status com Valor Inválido (Deve dar erro 400)

# Altere {ID_DO_RASCUNHO} para o ID real do rascunho que você quer atualizar
# Altere SEU_TOKEN_JWT para o seu token de acesso JWT válido
PATCH http://127.0.0.1:8000/api/rascunhos/3/update_status/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxNTkyNDQyLCJpYXQiOjE3NjE1ODg4NDIsImp0aSI6ImE5Mzc1ZjZkYzE0ZjQ3Nzg5ZTc4NDc3NmMyYmZiNDI2IiwidXNlcl9pZCI6IjEifQ.A0vb8JGaLspJp5nD-ORCD8b2k5lfGTL8MXv_1Zlz0tY
Content-Type: application/json

{
  "status": "INVALIDO"
}