# Generated by Django 5.2.7 on 2025-10-24 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clausula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('conteudo_padrao', models.TextField()),
                ('requer_anexo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('is_pessoa_juridica', models.BooleanField(default=False)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('rg', models.CharField(blank=True, max_length=12, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('outros_dados', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='RascunhoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_documento', models.CharField(blank=True, max_length=255)),
                ('partes_atribuidas', models.JSONField(default=dict)),
                ('variaveis_preenchidas', models.JSONField(default=dict)),
                ('clausulas_finais', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('REVISAO', 'Em Revisão'), ('FINALIZADO', 'Finalizado')], default='RASCUNHO', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateQualificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('is_pessoa_juridica', models.BooleanField(default=False)),
                ('template_html', models.TextField()),
                ('variaveis_necessarias', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='TipoParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anexos/')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('rascunho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='contracts.rascunhocontrato')),
            ],
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('clausulas_base', models.ManyToManyField(blank=True, to='contracts.clausula')),
                ('partes_requeridas', models.ManyToManyField(to='contracts.tipoparte')),
            ],
        ),
        migrations.AddField(
            model_name='rascunhocontrato',
            name='tipo_contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.tipocontrato'),
        ),
    ]
