# Generated by Django 5.2.7 on 2025-10-28 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoRascunho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('dados_rascunho', models.JSONField(default=dict)),
                ('rascunho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='contracts.rascunhocontrato')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
